[commands.swipe.three]
left_up = ""
right_up = ""
up = ""
left_down = ""
right_down = ""
down = ""
left = ""
right = ""

[commands.swipe.four]
left_up = ""
right_up = ""
up = "~/scripts/Touchpad.sh Enabled 1"
left_down = ""
right_down = ""
down = "~/scripts/Touchpad.sh Enabled 0"
left = "~/scripts/Workspace.sh Prev"
right = "~/scripts/Workspace.sh Next"
