[commands.swipe.three]
left_up = ""
right_up = ""
up = "i3-msg move up"
left_down = ""
right_down = ""
down = "i3-msg move down"
left = "i3-msg move left"
right = "i3-msg move right"

[commands.swipe.four]
left_up = ""
right_up = ""
up = "i3-msg workspace 0:openSUSE"
left_down = ""
right_down = ""
down = "i3-msg workspace 11:Desktop"
left = "i3-msg workspace prev"
right = "i3-msg workspace next"
